spring:
  datasource:
    # 连接池类型
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/yande11?serverTimezone=UTC
      username: root
      password: 986977

  servlet:
    multipart:
      max-file-size: 150MB  #设置单个文件大小
      max-request-size: 2048MB  #设置总上传的数据大小

  data:
    mongodb:
      uri: mongodb://localhost:27017/myDB

  elasticsearch:
    rest:
      uris: localhost:9200
      socket-timeout: 30000
      # username:
      # password:

server:
  port: 8090
  address: 0.0.0.0
  error:
    include-message: always
  servlet:
    context-path: /yandeApi

logging:
  config: classpath:config/logback-spring.xml

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

redis:
  max-total: 100
  max-wait-millis: 3000
  host: 127.0.0.1
  port: 6379

# 用户上传文件本地存放的地址
file-path:
  upload-save-path: D:\yande_imgdb_upload\

# 用户token保存时间
token-config:
  save-time: 1209600

# python爬虫脚本地址
python-script-path: D:\学习\python\yandeGET\xxl_job_task.py

# xxl-job 定时任务配置
xxl:
  job:
    accessToken: default_token
    admin:
      # 多个地址使用,分割
      addresses: http://127.0.0.1:9800/xxl-job-admin
    executor:
      appname: xxl-job-executor-yande
      address:
      ip:
      port: 8899
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
